# Define reusable preamble templates
preambles:
  base:
    - "#!/bin/bash"
    - "#SBATCH --partition=main"
    - "#SBATCH --output=test-%j.out"
    - "#SBATCH --error=test-%j.err"
  
  gpu:
    - "#SBATCH --gres=gpu:1"
    - "#SBATCH --mem=8G"

groups:
  - name: test-group
    sequentialjobs:
      - job:
          preamble: base
          # wait for 1 minute
          command: "echo 'First job' && sleep 60"
      - job:
          preamble: gpu
          command: "echo 'First job' && sleep 60"