# test.yaml
preambles:
  gpu4:   
    - "#!/bin/bash"
    - "#SBATCH --output=slurm/slurm-%j.out"
    - "#SBATCH --error=slurm/slurm-%j.err"   
    - "#SBATCH --partition=short-unkillable"
    - "#SBATCH --gres=gpu:a100l:4"
    - "#SBATCH --cpus-per-task=12"
    - "#SBATCH --mem=128G"
    - "#SBATCH --nodes=1"
    - "#SBATCH --time=3:00:00"
    - "source /home/mila/m/marawan.gamal/scratch/prod/tjdnet/.venv/bin/activate"


# Root group executed in sequence
group:
  name: "test-group"
  type: sequential
  jobs:
    - job:
        preamble: gpu4
        command: "python main.py train --accel_strategy fsdp --dataset gsm8k --model meta-llama/Llama-3.2-3B-Instruct --epochs 20 --batch_size 8 --seq_len 128 --lr 5e-4 --model_head base --rank 1 --horizon 1 --slurm_job_id $SLURM_JOB_ID"

    - job:
        preamble: gpu4
        command: "python main.py test --slurm_job_id $SLURM_JOB_ID"


