# test.yaml
preambles:
  gpu4:   
    - "#!/bin/bash"
    - "#SBATCH --output=slurm/slurm-%j.out"
    - "#SBATCH --error=slurm/slurm-%j.err"   
    - "#SBATCH --partition=short-unkillable"
    - "#SBATCH --gres=gpu:a100l:4"
    - "#SBATCH --cpus-per-task=12"
    - "#SBATCH --mem=128G"
    - "#SBATCH --nodes=1"
    - "#SBATCH --time=3:00:00"
    - "source /home/mila/m/marawan.gamal/scratch/tjdnet/.venv/bin/activate"

  cpu:
    - "#!/bin/bash"
    - "#SBATCH --output=slurm/slurm-%j.out"
    - "#SBATCH --error=slurm/slurm-%j.err"   
    - "#SBATCH --mem=128G"
    - "source /home/mila/m/marawan.gamal/scratch/tjdnet/.venv/bin/activate"


# Root group executed in sequence
group:
  name: "main"
  type: sequential
  jobs:
    # group_id: aaa-bbb
    - group:
        type: sweep
        preamble: gpu4
        sweep:
          lr: [1e-4]
        sweep_template:  "python main.py train --accel_strategy fsdp --dataset gsm8k --model distilbert/distilgpt2 --epochs 2 --max_num_samples 5 --batch_size 8 --seq_len 128 --lr {lr} --model_head base --rank 1 --horizon 1 --slurm_job_id $SLURM_JOB_ID --group_id {group_id}"

    # group_id: aaa-ccc
    - job:
        preamble: cpu
        command: "python scripts/tag_best.py --group_level 0 --group_id {group_id}"

    # group_id: aaa
    - job:
        preamble: gpu4
        command: "python main.py test --group_id {group_id}"


