# test.yaml
preambles:
  glong:   
    - "#!/bin/bash"
    - "#SBATCH --output=slurm/slurm-%j.out"
    - "#SBATCH --error=slurm/slurm-%j.err"   
    - "#SBATCH --partition=long"
    - "#SBATCH --gres=gpu:a100l:1"
    - "#SBATCH --mem=128G"
    - "#SBATCH --cpus-per-task=12"
    - "#SBATCH --nodes=1"
    - "source /home/mila/m/marawan.gamal/scratch/tjdnet/.venv/bin/activate"

  cshort:
    - "#!/bin/bash"
    - "#SBATCH --output=slurm/slurm-%j.out"
    - "#SBATCH --error=slurm/slurm-%j.err"   
    - "#SBATCH --partition=long-cpu"
    - "#SBATCH --mem=32G"
    - "source /home/mila/m/marawan.gamal/scratch/tjdnet/.venv/bin/activate"

# MAIN: meta-llama/Llama-3.2-3B-Instruct
# DEBUG: distilbert/distilgpt2

# Root group executed in sequence
group:
  # aaa
  name: "main"
  type: parallel
  jobs:

  ################################################
  #                 BASE                         #  
  ################################################


    # w/o speculation
    - group:
        # aaa-bbb
        name: "gsm8k:base"
        type: parallel
        jobs:
          #  Train on ShareGPT dataset
          #  1. Sweep over lr, rank, horizon
          - job:
              # aaa-bbb-XXXX
              preamble: glong
              command:  "python main.py fit --config config/config.yaml --trainer.max_epochs 10 --trainer.gradient_clip_val 1 --model.model lmsys/vicuna-7b-v1.5 --model.hidden_dim 4096 --model.horizon 1 --model.rank 1 --model.positivity_func safe_exp --data.batch_size 8 --data.dataset gsm8k --auto_lr_find"

          - job:
              # aaa-bbb-XXXX
              preamble: glong
              command:  "python main.py fit --config config/config.yaml --trainer.max_epochs 10 --trainer.gradient_clip_val 1 --model.model meta-llama/Llama-3.2-3B-Instruct --model.hidden_dim 8192 --model.horizon 1 --model.rank 1 --model.positivity_func safe_exp --data.batch_size 8 --data.dataset gsm8k --auto_lr_find"


  ################################################
  #                 CP                           #  
  ################################################


    # w/o speculation
    - group:
        # aaa-bbb
        name: "gsm8k:cp"
        type: parallel
        jobs:
          #  Train on ShareGPT dataset
          #  1. Sweep over lr, rank, horizon
          - job:
              # aaa-bbb-XXXX
              preamble: glong
              command:  "python main.py fit --config config/config.yaml --trainer.max_epochs 10 --trainer.gradient_clip_val 1 --model.model lmsys/vicuna-7b-v1.5 --model.hidden_dim 4096 --model.horizon 2 --model.rank 8 --model.model_head cp --model.positivity_func safe_exp --data.batch_size 8 --data.dataset gsm8k --auto_lr_find"

          - job:
              # aaa-bbb-XXXX
              preamble: glong
              command:  "python main.py fit --config config/config.yaml --trainer.max_epochs 10 --trainer.gradient_clip_val 1 --model.model meta-llama/Llama-3.2-3B-Instruct --model.hidden_dim 8192 --model.horizon 2 --model.rank 8 --model.model_head cp --model.positivity_func safe_exp --data.batch_size 8 --data.dataset gsm8k --auto_lr_find"
