# test.yaml
preambles:
  glong:   
    - "#!/bin/bash"
    - "#SBATCH --output=slurm/slurm-%j.out"
    - "#SBATCH --error=slurm/slurm-%j.err"   
    - "#SBATCH --partition=long"
    - "#SBATCH --gres=gpu:a100l:1"
    - "#SBATCH --mem=128G"
    - "#SBATCH --cpus-per-task=12"
    - "#SBATCH --nodes=1"
    - "source /home/mila/m/marawan.gamal/scratch/tjdnet/.venv/bin/activate"

  cshort:
    - "#!/bin/bash"
    - "#SBATCH --output=slurm/slurm-%j.out"
    - "#SBATCH --error=slurm/slurm-%j.err"   
    - "#SBATCH --partition=long-cpu"
    - "#SBATCH --mem=32G"
    - "source /home/mila/m/marawan.gamal/scratch/tjdnet/.venv/bin/activate"

# MAIN: meta-llama/Llama-3.2-3B-Instruct
# DEBUG: distilbert/distilgpt2

# Root group executed in sequence
group:
  # aaa
  name: "main"
  type: parallel
  jobs:

  ################################################
  #                 BASE                         #  
  ################################################


    # w/o speculation
    - group:
        # aaa-bbb
        name: "sharegpt:stp"
        type: sequential
        jobs:
          #  Train on ShareGPT dataset
          #  1. Sweep over lr, rank, horizon
          - group:
              # aaa-bbb-XXXX
              name: "sweep"
              type: sweep
              preamble: glong
              sweep: 
                lr: [1e-3]
                max_num_samples: [5000]
              sweep_template:  "python main.py fit --config config/config.yaml --trainer.max_epochs 1 --model.model lmsys/vicuna-7b-v1.5 --model.model_head stp --model.horizon 1 --model.rank 1 --model.positivity_func sigmoid --data.batch_size 8 --data.dataset sharegpt --data.max_num_samples {max_num_samples} --auto_lr_find"


  ################################################
  #                 CP                           #  
  ################################################


    - group:
        # aaa-bbb
        name: "sharegpt:cp"
        type: sequential
        jobs:
          #  Train on ShareGPT dataset
          #  1. Sweep over lr, rank, horizon
          - group:
              # aaa-bbb-XXXX
              name: "sweep"
              type: sweep
              preamble: glong
              sweep: 
                lr: [1e-3]
                max_num_samples: [5000]
                positivity_func: [sigmoid]
                horizon: [2]
              sweep_template:  "python main.py fit --config config/config.yaml --trainer.max_epochs 1 --trainer.gradient_clip_val 1.0 --model.model lmsys/vicuna-7b-v1.5 --model.horizon {horizon} --model.rank 8 --model.model_head cp --model.positivity_func {positivity_func} --data.batch_size 8 --data.dataset sharegpt --data.max_num_samples {max_num_samples} --auto_lr_find"
